# Generated by Django 5.0.6 on 2024-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CardImgFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='CardImgSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100, verbose_name='Card Title')),
                ('card_description_first', models.TextField(verbose_name='Card Description')),
                ('card_description_second', models.TextField(verbose_name='Card Description')),
            ],
        ),
        migrations.CreateModel(
            name='CareerHeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=' Title Hero')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hero Image')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('img_background', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='OffersCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('img_background', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='WyPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Sub Title')),
                ('img_background', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
            ],
        ),
    ]
