# Generated by Django 5.0.6 on 2024-06-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WyPay',
            new_name='WePay',
        ),
    ]
