# Generated by Django 5.0.6 on 2024-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_wypay_wepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
