# Generated by Django 5.0.6 on 2024-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=' Title ')),
                ('phone', models.CharField(max_length=100, verbose_name=' Phone')),
                ('phone_link', models.CharField(max_length=100, verbose_name=' Phone Link ')),
                ('email', models.EmailField(max_length=100, verbose_name=' Email')),
                ('email_link', models.CharField(max_length=100, verbose_name=' Email Link')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('location_link', models.CharField(max_length=100, verbose_name='location Link')),
                ('facebook', models.CharField(max_length=100, verbose_name=' Facebook')),
                ('facebook_link', models.CharField(max_length=100, verbose_name='facebook Link')),
                ('instagram', models.CharField(max_length=100, verbose_name='instagram')),
                ('instagram_link', models.CharField(max_length=100, verbose_name='instagram Link')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='iframe Google Maps')),
            ],
        ),
    ]
