# Generated by Django 5.0.6 on 2024-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='main_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Main Title '),
        ),
    ]
