# Generated by Django 5.0.6 on 2024-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_main_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_link',
        ),
    ]
