# Generated by Django 5.0.6 on 2024-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='form_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Form Title '),
        ),
    ]
