# Generated by Django 5.0.6 on 2024-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=100, verbose_name='Main Title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Main Image')),
                ('sub_title', models.TextField(blank=True, null=True, verbose_name='Main  Text ')),
            ],
        ),
        migrations.CreateModel(
            name='TextServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Main  Text ')),
            ],
        ),
    ]
