# Generated by Django 5.0.6 on 2024-06-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.DateField(verbose_name='Year of Manufacture'),
        ),
    ]
