# Generated by Django 5.0.6 on 2024-06-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_alter_truck_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='description',
            field=models.CharField(default='No description', max_length=255, verbose_name='Truck Description'),
        ),
    ]
