# Generated by Django 5.0.6 on 2024-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0005_truck_bargain_alter_truck_impact_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='trailer',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Trailer'),
        ),
    ]
