# Generated by Django 5.0.6 on 2024-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0006_truck_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Speed (km/h)'),
        ),
    ]
