# Generated by Django 5.0.6 on 2024-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_sub_title', models.CharField(max_length=100, verbose_name=' About Sub Title')),
                ('about_title', models.CharField(max_length=100, verbose_name=' About Title')),
                ('about_text', models.TextField(verbose_name=' About Text')),
                ('about_img', models.ImageField(upload_to='images/', verbose_name=' About Image')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100, verbose_name=' Main Title')),
                ('mail_background_img', models.ImageField(upload_to='images/', verbose_name=' Mail Background Image')),
                ('mail_card_title', models.CharField(max_length=100, verbose_name=' Mail Card Title')),
                ('mail_card_text', models.TextField(verbose_name=' Mail Card Text')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=100, verbose_name=' Services Title')),
                ('services_sub_title', models.CharField(max_length=100, verbose_name=' Services Sub Title')),
                ('service_title', models.CharField(max_length=100, verbose_name=' Service Title')),
                ('service_text', models.TextField(verbose_name=' Service Text')),
                ('service_img', models.ImageField(upload_to='images/', verbose_name=' Service Image')),
            ],
        ),
    ]
