# Generated by Django 5.0.6 on 2024-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(upload_to='images/', verbose_name=' About Image')),
            ],
        ),
        migrations.CreateModel(
            name='MailCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_card_title', models.CharField(max_length=100, verbose_name=' Mail Card Title')),
                ('mail_card_text', models.TextField(verbose_name=' Mail Card Text')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100, verbose_name=' Service Title')),
                ('service_text', models.TextField(verbose_name=' Service Text')),
                ('service_img', models.ImageField(upload_to='images/', verbose_name=' Service Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_img',
        ),
        migrations.RemoveField(
            model_name='main',
            name='mail_card_text',
        ),
        migrations.RemoveField(
            model_name='main',
            name='mail_card_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_img',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_title',
        ),
    ]
