# Generated by Django 5.0.6 on 2024-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutcardimg_mailcard_serviceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcardimg',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
