# Generated by Django 5.0.6 on 2024-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_about_delete_aboutcardimg_delete_mailcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='about_img',
            new_name='about_img_first',
        ),
        migrations.RemoveField(
            model_name='main',
            name='description',
        ),
        migrations.RemoveField(
            model_name='main',
            name='main_card_text',
        ),
        migrations.RemoveField(
            model_name='main',
            name='main_card_title',
        ),
        migrations.RemoveField(
            model_name='main',
            name='service_img',
        ),
        migrations.RemoveField(
            model_name='main',
            name='service_text',
        ),
        migrations.AddField(
            model_name='main',
            name='about_description_first',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' About Description First'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_description_fourth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' About Description Fourth'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_description_second',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' About Description Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_description_third',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' About Description Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_img_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_img_second',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_img_third',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_background_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Careers Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_card_img_first',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Careers Card Image First'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_card_img_second',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Careers Card Image Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_card_img_third',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Careers Card Image Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_description_first',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Careers Description First'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_description_second',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Careers Description Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_description_third',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Careers Description Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_sub_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Careers Sub Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_text',
            field=models.TextField(default='No text', verbose_name=' Careers Text'),
        ),
        migrations.AddField(
            model_name='main',
            name='careers_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Careers Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='development_background_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Development Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='development_sub_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Development Sub Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='development_text',
            field=models.TextField(default='No text', verbose_name=' Development Text'),
        ),
        migrations.AddField(
            model_name='main',
            name='development_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Development Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_text_first',
            field=models.TextField(blank=True, null=True, verbose_name='Main Card Text First'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_text_second',
            field=models.TextField(blank=True, null=True, verbose_name='Main Card Text Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_text_three',
            field=models.TextField(blank=True, null=True, verbose_name='Main Card Text Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_title_first',
            field=models.CharField(default='No title', max_length=100, verbose_name='Main Card Title First'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_title_second',
            field=models.CharField(default='No title', max_length=100, verbose_name='Main Card Title Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_card_title_three',
            field=models.CharField(default='No title', max_length=100, verbose_name='Main Card Title Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='projects_card_background_img_first',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Projects Card Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='projects_card_background_img_second',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=' Projects Card Image'),
        ),
        migrations.AddField(
            model_name='main',
            name='projects_card_title_first',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Projects Card Title First'),
        ),
        migrations.AddField(
            model_name='main',
            name='projects_card_title_second',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Projects Card Title Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='projects_main_title',
            field=models.CharField(default='No title', max_length=100, verbose_name=' Projects Main Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_description_first',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Description First'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_description_fourth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Description Fourth'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_description_second',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Description Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_description_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Description Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_img_first',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Service Image First'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_img_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Service Image Fourth'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_img_second',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Service Image Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_img_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Service Image Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_sub_title',
            field=models.CharField(default='No title', max_length=100, verbose_name='Service Sub Title'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_text_first',
            field=models.TextField(default='No text', verbose_name='Service Text First'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_text_fourth',
            field=models.TextField(default='No text', verbose_name='Service Text Fourth'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_text_second',
            field=models.TextField(default='No text', verbose_name='Service Text Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_text_three',
            field=models.TextField(default='No text', verbose_name='Service Text Third'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_title_first',
            field=models.CharField(default='No title', max_length=100, verbose_name='Service Title First'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_title_fourth',
            field=models.CharField(default='No title', max_length=100, verbose_name='Service Title Fourth'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_title_second',
            field=models.CharField(default='No title', max_length=100, verbose_name='Service Title Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='service_title_three',
            field=models.CharField(default='No title', max_length=100, verbose_name='Service Title Third'),
        ),
    ]
