# Generated by Django 5.0.6 on 2024-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Link_first',
            field=models.CharField(default='No title', max_length=100, verbose_name='Link First'),
        ),
        migrations.AddField(
            model_name='main',
            name='Link_second',
            field=models.CharField(default='No title', max_length=100, verbose_name='Link Second'),
        ),
        migrations.AddField(
            model_name='main',
            name='Link_third',
            field=models.CharField(default='No title', max_length=100, verbose_name='Link Third'),
        ),
    ]
