# Generated by Django 5.0.6 on 2024-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_abouthero_main_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCardTeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='No title', max_length=100, verbose_name='Card Name')),
                ('card_position', models.CharField(default='No title', max_length=100, verbose_name='Card Position')),
                ('card_img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Card Image')),
                ('card_description', models.TextField(blank=True, null=True, verbose_name='Card Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aboutteem',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='aboutteem',
            name='card_img',
        ),
        migrations.RemoveField(
            model_name='aboutteem',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='aboutteem',
            name='card_position',
        ),
    ]
